habitat-sh/core-packages

packages/development/libraries/inputproto/.hab-plan-config.toml, packages/development/libraries/inputproto/README.md, packages/development/libraries/inputproto/plan.sh, packages/development/tools/misc/inotify-tools/.hab-plan-config.toml, packages/development/tools/misc/inotify-tools/README.md, packages/development/tools/misc/inotify-tools/plan.sh, packages/development/tools/misc/intltool/.hab-plan-config.toml, packages/development/tools/misc/intltool/README.md, packages/development/tools/misc/intltool/intltool-0.51.0-perl-5.26.patch, packages/development/tools/misc/intltool/plan.sh, packages/os-specific/linux/iproute2/.hab-plan-config.toml, packages/os-specific/linux/iproute2/README.md, packages/os-specific/linux/iproute2/plan.sh, packages/os-specific/linux/iproute2/x86_64-linux-kernel2/plan.sh, packages/os-specific/linux/iptables/.hab-plan-config.toml, packages/os-specific/linux/iptables/README.md, packages/os-specific/linux/iptables/plan.sh, packages/os-specific/linux/ipvsadm/.hab-plan-config.toml, packages/os-specific/linux/ipvsadm/Makefile.patch, packages/os-specific/linux/ipvsadm/README.md, packages/os-specific/linux/ipvsadm/plan.sh
https://chefio.atlassian.net/browse/CHEF-4318
=> Moving packages from core-plans to core-packages[chef-4318]

packages/development/libraries/glibc/x86_64-linux-kernel2/0005-fix-binutils-2-29-build.patch, packages/development/libraries/glibc/x86_64-linux-kernel2/dont-use-system-ld-so.patch, packages/development/libraries/glibc/x86_64-linux-kernel2/gcc-implicit-boolean.patch, packages/development/libraries/glibc/x86_64-linux-kernel2/glibc-2.23-upstream_fixes-1.patch, packages/development/libraries/glibc/x86_64-linux-kernel2/nss-nisplus-gcc7.patch, packages/development/libraries/glibc/x86_64-linux-kernel2/plan.sh, packages/development/libraries/glibc/x86_64-linux-kernel2/remove-sun-rpm-bug.patch, packages/development/libraries/glibc/x86_64-linux-kernel2/rpcgen-path.patch, packages/development/libraries/glibc/x86_64-linux-kernel2/testsuite-fix.patch
https://chefio.atlassian.net/browse/CHEF-4319
=> Moving packages from core-plans to core-packages[chef-4319]

packages/applications/virtualization/docker/credential-helper/plan.ps1, packages/applications/virtualization/docker/default/x86_64-windows/plan.ps1, packages/development/tools/build-managers/dmake/README.md, packages/development/tools/build-managers/dmake/plan.ps1, packages/os-specific/windows/dotnet-dev-pack/45/README.md, packages/os-specific/windows/dotnet-dev-pack/45/plan.ps1, packages/os-specific/windows/dotnet-dev-pack/462/README.md, packages/os-specific/windows/dotnet-dev-pack/462/plan.ps1, packages/os-specific/windows/dotnet-runtime/35sp1/README.md, packages/os-specific/windows/dotnet-runtime/35sp1/hooks/install, packages/os-specific/windows/dotnet-runtime/35sp1/plan.ps1, packages/os-specific/windows/dotnet-runtime/45/README.md, packages/os-specific/windows/dotnet-runtime/45/hooks/install, packages/os-specific/windows/dotnet-runtime/45/plan.ps1
https://chefio.atlassian.net/browse/CHEF-4672
=> Moving packages from core-plans to core-packages[chef-4672]

packages/applications/misc/exercism/.hab-plan-config.toml, packages/applications/misc/exercism/README.md, packages/applications/misc/exercism/default.toml, packages/applications/misc/exercism/plan.sh, packages/applications/servers/etcd/.hab-plan-config.toml, packages/applications/servers/etcd/README.md, packages/applications/servers/etcd/config/conf.yml, packages/applications/servers/etcd/default.toml, packages/applications/servers/etcd/hooks/health-check, packages/applications/servers/etcd/hooks/health_check, packages/applications/servers/etcd/hooks/run, packages/applications/servers/etcd/plan.sh, packages/development/interpreters/erlang/21/.hab-plan-config.toml, packages/development/interpreters/erlang/21/README.md, packages/development/interpreters/erlang/21/plan.sh, packages/development/interpreters/erlang/22/.hab-plan-config.toml, packages/development/interpreters/erlang/22/README.md, packages/development/interpreters/erlang/22/plan.sh, packages/development/interpreters/erlang/24/.hab-plan-config.toml, packages/development/interpreters/erlang/24/README.md, packages/development/interpreters/erlang/24/plan.sh, packages/os-specific/linux/eudev/.hab-plan-config.toml, packages/os-specific/linux/eudev/README.md, packages/os-specific/linux/eudev/plan.sh, packages/tools/misc/fd/.hab-plan-config.toml, packages/tools/misc/fd/README.md, packages/tools/misc/fd/plan.sh
https://chefio.atlassian.net/browse/CHEF-4306
=> move plans from core-plans repo,chef4306

packages/data/fonts/liberation-fonts-ttf/.hab-plan-config.toml, packages/data/fonts/liberation-fonts-ttf/README.md, packages/data/fonts/liberation-fonts-ttf/plan.sh, packages/development/compilers/llvm/5/libcxx/.hab-plan-config.toml, packages/development/compilers/llvm/5/libcxx/README.md, packages/development/compilers/llvm/5/libcxx/plan.sh, packages/development/compilers/llvm/5/libcxxabi/.hab-plan-config.toml, packages/development/compilers/llvm/5/libcxxabi/README.md, packages/development/compilers/llvm/5/libcxxabi/plan.sh, packages/development/libraries/libcerf/.hab-plan-config.toml, packages/development/libraries/libcerf/plan.sh, packages/development/libraries/libdrm/.hab-plan-config.toml, packages/development/libraries/libdrm/README.md, packages/development/libraries/libdrm/plan.sh, packages/development/libraries/libepoxy/.hab-plan-config.toml, packages/development/libraries/libepoxy/README.md, packages/development/libraries/libepoxy/plan.sh, packages/development/libraries/libestr/.hab-plan-config.toml, packages/development/libraries/libestr/README.md, packages/development/libraries/libestr/plan.sh, packages/development/libraries/libev/.hab-plan-config.toml, packages/development/libraries/libev/README.md, packages/development/libraries/libev/plan.sh, packages/os-specific/linux/libcap-ng/.hab-plan-config.toml, packages/os-specific/linux/libcap-ng/README.md, packages/os-specific/linux/libcap-ng/plan.sh
https://chefio.atlassian.net/browse/CHEF-4591
=> Moving packages from core-plans to core-packages[chef-4591]

packages/applications/misc/github-changelog/README.md, packages/applications/misc/github-changelog/plan.sh, packages/development/compilers/ghc/82/.hab-plan-config.toml, packages/development/compilers/ghc/82/README.md, packages/development/compilers/ghc/82/plan.sh, packages/development/compilers/ghc/84/.hab-plan-config.toml, packages/development/compilers/ghc/84/README.md, packages/development/compilers/ghc/84/plan.sh, packages/development/compilers/ghc/86/.hab-plan-config.toml, packages/development/compilers/ghc/86/plan.ps1, packages/development/compilers/ghc/86/plan.sh, packages/development/compilers/ghc/88/.hab-plan-config.toml, packages/development/compilers/ghc/88/README.md, packages/development/compilers/ghc/88/plan.sh, packages/development/compilers/ghc/bootstrap/.hab-plan-config.toml, packages/development/compilers/ghc/bootstrap/README.md, packages/development/compilers/ghc/bootstrap/plan.sh, packages/development/libraries/giflib/.hab-plan-config.toml, packages/development/libraries/giflib/README.md, packages/development/libraries/giflib/plan.sh, packages/development/libraries/glib/.hab-plan-config.toml, packages/development/libraries/glib/README.md, packages/development/libraries/glib/plan.sh, packages/development/tools/misc/gifsicle/.hab-plan-config.toml, packages/development/tools/misc/gifsicle/README.md, packages/development/tools/misc/gifsicle/plan.sh
migrating package from core-plans repo to core-packages repo; https://chefio.atlassian.net/browse/CHEF-4310
=> migrating packages from core-plans

packages/development/compilers/ghc/default/.hab-plan-config.toml, packages/development/compilers/ghc/default/README.md, packages/development/compilers/ghc/default/plan.ps1, packages/development/compilers/ghc/default/plan.sh, packages/development/libraries/gdk-pixbuf/.hab-plan-config.toml, packages/development/libraries/gdk-pixbuf/README.md, packages/development/libraries/gdk-pixbuf/plan.sh, packages/development/libraries/gecode/.hab-plan-config.toml, packages/development/libraries/gecode/README.md, packages/development/libraries/gecode/plan.sh, packages/development/tools/misc/gdb/.hab-plan-config.toml, packages/development/tools/misc/gdb/README.md, packages/development/tools/misc/gdb/config.h-fix.patch, packages/development/tools/misc/gdb/plan.sh
https://chefio.atlassian.net/browse/CHEF-4309
=> move plans from core-plans repo,chef4309

packages/applications/servers/http/leproxy/.hab-plan-config.toml, packages/applications/servers/http/leproxy/README.md, packages/applications/servers/http/leproxy/plan.sh, packages/development/libraries/leveldb/README.md, packages/development/libraries/leveldb/plan.sh, packages/development/libraries/libarchive-musl/.hab-plan-config.toml, packages/development/libraries/libarchive-musl/README.md, packages/development/libraries/libarchive-musl/plan.sh, packages/development/libraries/libatomic_ops/.hab-plan-config.toml, packages/development/libraries/libatomic_ops/README.md, packages/development/libraries/libatomic_ops/plan.sh, packages/os-specific/linux/libaio/.hab-plan-config.toml, packages/os-specific/linux/libaio/README.md, packages/os-specific/linux/libaio/plan.sh
https://chefio.atlassian.net/browse/CHEF-4590
=> Moving packages from core-plans to core-packages[chef-4590]

packages/development/libraries/libfastjson/.hab-plan-config.toml, packages/development/libraries/libfastjson/README.md, packages/development/libraries/libfastjson/plan.sh, packages/development/libraries/libfcgi/.hab-plan-config.toml, packages/development/libraries/libfcgi/README.md, packages/development/libraries/libfcgi/plan.sh, packages/development/libraries/libfcgi/stdio.patch, packages/development/libraries/libgcrypt/.hab-plan-config.toml, packages/development/libraries/libgcrypt/README.md, packages/development/libraries/libgcrypt/plan.sh, packages/development/libraries/libgd/.hab-plan-config.toml, packages/development/libraries/libgd/plan.sh, packages/development/libraries/libghthash/.hab-plan-config.toml, packages/development/libraries/libghthash/README.md, packages/development/libraries/libghthash/plan.sh, packages/development/libraries/libice/.hab-plan-config.toml, packages/development/libraries/libice/README.md, packages/development/libraries/libice/plan.sh
https://chefio.atlassian.net/browse/CHEF-4594
=> Moving packages from core-plans to core-packages[chef-4594]

packages/development/libraries/libimagequant/.hab-plan-config.toml, packages/development/libraries/libimagequant/README.md, packages/development/libraries/libimagequant/plan.sh, packages/development/libraries/libksba/.hab-plan-config.toml, packages/development/libraries/libksba/README.md, packages/development/libraries/libksba/plan.sh, packages/development/libraries/libnsl/.hab-plan-config.toml, packages/development/libraries/libnsl/README.md, packages/development/libraries/libnsl/autogen.patch, packages/development/libraries/libnsl/plan.sh, packages/os-specific/linux/libnl/.hab-plan-config.toml, packages/os-specific/linux/libnl/plan.sh
https://chefio.atlassian.net/browse/CHEF-4595
=> Moving packages from core-plans to core-packages[chef-4595]

packages/applications/servers/http/tomcat/native/.hab-plan-config.toml, packages/applications/servers/http/tomcat/native/README.md, packages/applications/servers/http/tomcat/native/plan.sh, packages/applications/servers/monitoring/telegraf/.hab-plan-config.toml, packages/applications/servers/monitoring/telegraf/README.md, packages/applications/servers/monitoring/telegraf/config/telegraf.conf, packages/applications/servers/monitoring/telegraf/plan.sh, packages/development/tools/misc/terraform/.hab-plan-config.toml, packages/development/tools/misc/terraform/README.md, packages/development/tools/misc/terraform/plan.sh, packages/tools/misc/tap-xunit/.hab-plan-config.toml, packages/tools/misc/tap-xunit/README.md, packages/tools/misc/tap-xunit/plan.sh, packages/tools/misc/tlog/.hab-plan-config.toml, packages/tools/misc/tlog/README.md, packages/tools/misc/tlog/plan.sh, packages/tools/misc/tmux/.hab-plan-config.toml, packages/tools/misc/tmux/README.md, packages/tools/misc/tmux/plan.sh, packages/tools/networking/tcpdump/.hab-plan-config.toml, packages/tools/networking/tcpdump/README.md, packages/tools/networking/tcpdump/plan.sh
https://chefio.atlassian.net/browse/CHEF-4637
=> move plans from core-plans repo,chef4637

packages/development/libraries/libpcap/.hab-plan-config.toml, packages/development/libraries/libpcap/README.md, packages/development/libraries/libpcap/plan.sh, packages/development/libraries/libpciaccess/.hab-plan-config.toml, packages/development/libraries/libpciaccess/README.md, packages/development/libraries/libpciaccess/plan.sh, packages/development/libraries/libpipeline/.hab-plan-config.toml, packages/development/libraries/libpipeline/README.md, packages/development/libraries/libpipeline/plan.sh, packages/development/libraries/libpq/.hab-plan-config.toml, packages/development/libraries/libpq/README.md, packages/development/libraries/libpq/plan.sh, packages/development/libraries/libpthread-stubs/.hab-plan-config.toml, packages/development/libraries/libpthread-stubs/README.md, packages/development/libraries/libpthread-stubs/plan.sh, packages/development/libraries/libressl-musl/.hab-plan-config.toml, packages/development/libraries/libressl-musl/README.md, packages/development/libraries/libressl-musl/plan.sh, packages/development/libraries/libressl/.hab-plan-config.toml, packages/development/libraries/libressl/README.md, packages/development/libraries/libressl/plan.sh, packages/development/libraries/libscrypt/.hab-plan-config.toml, packages/development/libraries/libscrypt/README.md, packages/development/libraries/libscrypt/plan.sh
https://chefio.atlassian.net/browse/CHEF-4596
=> Moving packages from core-plans to core-packages[chef-4596]

packages/applications/servers/varnish/.hab-plan-config.toml, packages/applications/servers/varnish/README.md, packages/applications/servers/varnish/config/varnish.default.vcl, packages/applications/servers/varnish/default.toml, packages/applications/servers/varnish/hooks/run, packages/applications/servers/varnish/patches/000-configure.patch, packages/applications/servers/varnish/plan.sh, packages/development/libraries/userspace-rcu/.hab-plan-config.toml, packages/development/libraries/userspace-rcu/README.md, packages/development/libraries/userspace-rcu/plan.sh, packages/development/libraries/utf8proc/.hab-plan-config.toml, packages/development/libraries/utf8proc/README.md, packages/development/libraries/utf8proc/plan.sh, packages/development/tools/misc/util-macros/.hab-plan-config.toml, packages/development/tools/misc/util-macros/README.md, packages/development/tools/misc/util-macros/plan.sh, packages/tools/networking/vde2/.hab-plan-config.toml, packages/tools/networking/vde2/README.md, packages/tools/networking/vde2/plan.sh, packages/tools/security/vault/.hab-plan-config.toml, packages/tools/security/vault/README.md, packages/tools/security/vault/config/settings.hcl, packages/tools/security/vault/default.toml, packages/tools/security/vault/hooks/init, packages/tools/security/vault/hooks/run, packages/tools/security/vault/plan.sh
https://chefio.atlassian.net/browse/CHEF-4639
=> move plans from core-plans repo,chef4639

packages/development/libraries/libxdmcp/.hab-plan-config.toml, packages/development/libraries/libxdmcp/README.md, packages/development/libraries/libxdmcp/plan.sh, packages/development/libraries/libxext/.hab-plan-config.toml, packages/development/libraries/libxext/README.md, packages/development/libraries/libxext/plan.sh, packages/development/libraries/libxfixes/.hab-plan-config.toml, packages/development/libraries/libxfixes/README.md, packages/development/libraries/libxfixes/plan.sh, packages/development/libraries/libxi/.hab-plan-config.toml, packages/development/libraries/libxi/README.md, packages/development/libraries/libxi/plan.sh, packages/development/libraries/libxmu/.hab-plan-config.toml, packages/development/libraries/libxmu/README.md, packages/development/libraries/libxmu/plan.sh, packages/development/libraries/libxrandr/.hab-plan-config.toml, packages/development/libraries/libxrandr/README.md, packages/development/libraries/libxrandr/plan.sh, packages/development/libraries/libxrender/.hab-plan-config.toml, packages/development/libraries/libxrender/README.md, packages/development/libraries/libxrender/plan.sh, packages/development/libraries/libxscrnsaver/.hab-plan-config.toml, packages/development/libraries/libxscrnsaver/README.md, packages/development/libraries/libxscrnsaver/plan.sh, packages/development/libraries/libxshmfence/.hab-plan-config.toml, packages/development/libraries/libxshmfence/README.md, packages/development/libraries/libxshmfence/plan.sh
https://chefio.atlassian.net/browse/CHEF-4599
=> Moving packages from core-plans to core-packages[chef-4599]

packages/development/libraries/libsm/.hab-plan-config.toml, packages/development/libraries/libsm/README.md, packages/development/libraries/libsm/plan.sh, packages/development/libraries/libsodium-musl/.hab-plan-config.toml, packages/development/libraries/libsodium-musl/README.md, packages/development/libraries/libsodium-musl/plan.sh, packages/development/libraries/libsodium/README.md, packages/development/libraries/libsodium/plan.ps1, packages/development/libraries/libssh2/.hab-plan-config.toml, packages/development/libraries/libssh2/README.md, packages/development/libraries/libssh2/plan.sh, packages/development/libraries/libtalloc/.hab-plan-config.toml, packages/development/libraries/libtalloc/README.md, packages/development/libraries/libtalloc/plan.sh, packages/development/libraries/libtasn1/.hab-plan-config.toml, packages/development/libraries/libtasn1/README.md, packages/development/libraries/libtasn1/plan.sh, packages/development/libraries/libtermkey/.hab-plan-config.toml, packages/development/libraries/libtermkey/README.md, packages/development/libraries/libtermkey/plan.sh, packages/development/libraries/libtirpc/.hab-plan-config.toml, packages/development/libraries/libtirpc/README.md, packages/development/libraries/libtirpc/plan.sh
https://chefio.atlassian.net/browse/CHEF-4597
=> Moving packages from core-plans to core-packages[chef-4597]

packages/development/interpreters/python/2/README.md, packages/development/interpreters/python/2/plan.ps1, packages/development/interpreters/python/34/README.md, packages/development/interpreters/python/34/plan.ps1, packages/development/interpreters/python/36/README.md, packages/development/interpreters/python/36/plan.ps1, packages/development/interpreters/python/37/README.md, packages/development/interpreters/python/37/plan.ps1, packages/development/interpreters/python/38/README.md, packages/development/interpreters/python/38/plan.ps1, packages/development/interpreters/python/39/README.md, packages/development/interpreters/python/39/plan.ps1, packages/development/interpreters/python/default/README.md, packages/development/interpreters/python/default/plan.ps1, packages/development/interpreters/python/default/x86_64-linux-kernel2/plan.sh, packages/development/libraries/protobuf/README.md, packages/development/libraries/protobuf/plan.ps1, packages/misc/ps-lock/PSLock.psd1, packages/misc/ps-lock/PSLock.psm1, packages/misc/ps-lock/README.md, packages/misc/ps-lock/plan.ps1, packages/misc/psscriptanalyser/README.md, packages/misc/psscriptanalyser/plan.ps1, packages/misc/psscriptanalyser/plan.sh
migrating packages from core-plans to core-packages repo; https://chefio.atlassian.net/browse/CHEF-4678
=> migrating packages from core-plans repo

packages/development/compilers/ocaml/.hab-plan-config.toml, packages/development/compilers/ocaml/README.md, packages/development/compilers/ocaml/plan.sh, packages/development/compilers/openjdk/11/.hab-plan-config.toml, packages/development/compilers/openjdk/11/README.md, packages/development/compilers/openjdk/11/plan.sh, packages/development/libraries/openjpeg/.hab-plan-config.toml, packages/development/libraries/openjpeg/README.md, packages/development/libraries/openjpeg/plan.sh, packages/development/tools/ocaml/ocamlbuild/.hab-plan-config.toml, packages/development/tools/ocaml/ocamlbuild/README.md, packages/development/tools/ocaml/ocamlbuild/plan.sh, packages/development/tools/ocaml/opam/.hab-plan-config.toml, packages/development/tools/ocaml/opam/README.md, packages/development/tools/ocaml/opam/plan.sh, packages/development/tools/omniORB/.hab-plan-config.toml, packages/development/tools/omniORB/README.md, packages/development/tools/omniORB/plan.sh, packages/development/tools/opa/.hab-plan-config.toml, packages/development/tools/opa/README.md, packages/development/tools/opa/default.toml, packages/development/tools/opa/hooks/run, packages/development/tools/opa/plan.sh, packages/os-specific/linux/numactl/.hab-plan-config.toml, packages/os-specific/linux/numactl/README.md, packages/os-specific/linux/numactl/plan.sh
https://chefio.atlassian.net/browse/CHEF-4612
=> move plans from core-plans repo,chef4612

packages/development/interpreters/ruby/25/.hab-plan-config.toml, packages/development/interpreters/ruby/25/README.md, packages/development/interpreters/ruby/25/plan.sh, packages/development/interpreters/ruby/26/.hab-plan-config.toml, packages/development/interpreters/ruby/26/README.md, packages/development/interpreters/ruby/26/plan.sh, packages/development/interpreters/ruby/default/.hab-plan-config.toml, packages/development/interpreters/ruby/default/README.md, packages/development/interpreters/ruby/default/plan.sh, packages/tools/archivers/rpm2cpio/.hab-plan-config.toml, packages/tools/archivers/rpm2cpio/README.md, packages/tools/archivers/rpm2cpio/hab-path.patch, packages/tools/archivers/rpm2cpio/plan.sh, packages/tools/misc/rlwrap/.hab-plan-config.toml, packages/tools/misc/rlwrap/README.md, packages/tools/misc/rlwrap/plan.sh, packages/tools/misc/rpcsvc-proto/.hab-plan-config.toml, packages/tools/misc/rpcsvc-proto/README.md, packages/tools/misc/rpcsvc-proto/plan.sh, packages/tools/package-management/rpm/.hab-plan-config.toml, packages/tools/package-management/rpm/README.md, packages/tools/package-management/rpm/plan.sh, packages/tools/security/rngd/.hab-plan-config.toml, packages/tools/security/rngd/plan.sh
https://chefio.atlassian.net/browse/CHEF-4623.
=> Moving packages from core-plans to core-packages[chef-4623]

packages/development/libraries/pango/.hab-plan-config.toml, packages/development/libraries/pango/README.md, packages/development/libraries/pango/plan.sh, packages/development/libraries/science/benchmark/papi/.hab-plan-config.toml, packages/development/libraries/science/benchmark/papi/README.md, packages/development/libraries/science/benchmark/papi/plan.sh, packages/development/tools/packer/.hab-plan-config.toml, packages/development/tools/packer/README.md, packages/development/tools/packer/plan.ps1, packages/development/tools/packer/plan.sh, packages/misc/pester/.hab-plan-config.toml, packages/misc/pester/README.md, packages/misc/pester/plan.ps1, packages/misc/pester/plan.sh, packages/os-specific/linux/pax-utils/.hab-plan-config.toml, packages/os-specific/linux/pax-utils/README.md, packages/os-specific/linux/pax-utils/plan.sh, packages/tools/backup/percona-xtrabackup/.hab-plan-config.toml, packages/tools/backup/percona-xtrabackup/README.md, packages/tools/backup/percona-xtrabackup/plan.sh
https://chefio.atlassian.net/browse/CHEF-4614
=> move plans from core-plans repo,chef4614

packages/tools/security/firejail/plan.sh
adding firejail package; https://chefio.atlassian.net/browse/CHEF-6778
=> adding firejail package

packages/bootstrap/build-tools/cross-tools/build-tools-coreutils/.hab-plan-config.toml, packages/bootstrap/build-tools/cross-tools/build-tools-coreutils/plan.sh, packages/bootstrap/stage1/coreutils/.hab-plan-config.toml, packages/bootstrap/stage1/coreutils/plan.sh, packages/tools/misc/coreutils/.hab-plan-config.toml, packages/tools/misc/coreutils/plan.sh
=> [coreutils] upgraded to v9.4

packages/bootstrap/build-tools/cross-tools/build-tools-findutils/.hab-plan-config.toml, packages/bootstrap/build-tools/cross-tools/build-tools-findutils/plan.sh, packages/tools/misc/findutils/.hab-plan-config.toml, packages/tools/misc/findutils/plan.sh
=> [findutils] fix for missing license files

packages/bootstrap/build-tools/cross-tools/build-tools-gzip/.hab-plan-config.toml, packages/bootstrap/build-tools/cross-tools/build-tools-gzip/plan.sh, packages/tools/compression/gzip/.hab-plan-config.toml, packages/tools/compression/gzip/plan.sh
=> [gzip] upgraded to v1.13

packages/bootstrap/build-tools/cross-tools/build-tools-sed/.hab-plan-config.toml, packages/bootstrap/build-tools/cross-tools/build-tools-sed/plan.sh, packages/tools/text/sed/.hab-plan-config.toml, packages/tools/text/sed/plan.sh
=> [sed] upgraded to v4.9

packages/bootstrap/build-tools/cross-tools/build-tools-gawk/.hab-plan-config.toml, packages/bootstrap/build-tools/cross-tools/build-tools-gawk/plan.sh, packages/tools/text/gawk/.hab-plan-config.toml, packages/tools/text/gawk/plan.sh
=> [gawk] upgraded to v5.3.0

packages/tools/networking/rsync/plan.sh
=> [rsync] change to include license files in package

packages/bootstrap/stage0/zlib/.hab-plan-config.toml, packages/bootstrap/stage0/zlib/plan.sh, packages/bootstrap/stage1/zlib/.hab-plan-config.toml, packages/bootstrap/stage1/zlib/plan.sh, packages/development/libraries/zlib/.hab-plan-config.toml, packages/development/libraries/zlib/plan.sh
https://chefio.atlassian.net/browse/CHEF-11545
=> zlib bumped to 1.3.1 [CHEF-11545]

packages/bootstrap/stage1/ncurses/.hab-plan-config.toml, packages/bootstrap/stage1/ncurses/plan.sh, packages/development/libraries/ncurses/.hab-plan-config.toml, packages/development/libraries/ncurses/plan.sh
https://chefio.atlassian.net/browse/CHEF-11541
=> ncurses bumped to 6.4 [CHEF-11541]

packages/applications/databases/sqlite/.hab-plan-config.toml, packages/applications/databases/sqlite/plan.sh
=> [sqlite] upgraded to v3.45.3

packages/applications/editors/vim/.hab-plan-config.toml, packages/applications/editors/vim/plan.sh
=> update vim to 9.1.0318

packages/applications/editors/mg/.hab-plan-config.toml, packages/applications/editors/mg/plan.sh
=> update mg to 20230501

packages/development/interpreters/erlang/.hab-plan-config.toml, packages/development/interpreters/erlang/plan.sh
=> update erlang to 26.2.2

packages/applications/servers/nginx/.hab-plan-config.toml, packages/applications/servers/nginx/plan.sh
=> update nginx to 1.25.3

packages/bootstrap/stage0/zlib/.hab-plan-config.toml, packages/bootstrap/stage0/zlib/plan.sh, packages/bootstrap/stage1/zlib/.hab-plan-config.toml, packages/bootstrap/stage1/zlib/plan.sh, packages/development/libraries/zlib/.hab-plan-config.toml, packages/development/libraries/zlib/plan.sh
https://chefio.atlassian.net/browse/CHEF-11545
=> typo error for checksum value [chef-11545]

packages/bootstrap/build-tools/cross-tools/build-tools-ncurses/.hab-plan-config.toml, packages/bootstrap/build-tools/cross-tools/build-tools-ncurses/plan.sh
https://chefio.atlassian.net/browse/CHEF-11541
=> build-tools-ncurses bumped to 6.4 [CHEF-11541]

packages/bootstrap/build-tools/cross-tools/build-tools-cacerts/.hab-plan-config.toml, packages/bootstrap/build-tools/cross-tools/build-tools-cacerts/plan.sh, packages/data/cacerts/.hab-plan-config.toml, packages/data/cacerts/plan.sh
=> update cacerts to 2023.12.12

packages/development/libraries/libedit/plan.sh
update libedit to 20230828-3.1
=> update libedit to 20230828-3.1

packages/development/tools/build-managers/make/.hab-plan-config.toml, packages/development/tools/build-managers/make/plan.sh
=> Update make to 4.4.1

packages/os-specific/linux/procps-ng/.hab-plan-config.toml, packages/os-specific/linux/procps-ng/plan.sh
=> update procps-ng to 4.0.4

packages/development/tools/misc/aws-cli/.hab-plan-config.toml, packages/development/tools/misc/aws-cli/plan.sh
=> [aws-cli] upgraded to v2.15.38

packages/development/libraries/readline/.hab-plan-config.toml, packages/development/libraries/readline/plan.sh
=> [readline] updated license files in package

packages/bootstrap/build-tools/host-tools/native-busybox-static/.hab-plan-config.toml, packages/bootstrap/build-tools/host-tools/native-busybox-static/plan.sh, packages/os-specific/linux/busybox/static/.hab-plan-config.toml, packages/os-specific/linux/busybox/static/plan.sh
=> [busybox] upgraded to v1.36.1

packages/applications/editors/mg/.hab-plan-config.toml, packages/applications/editors/vim/.hab-plan-config.toml, packages/applications/editors/vim/plan.sh, packages/bootstrap/build-tools/cross-tools/build-tools-findutils/plan.sh, packages/bootstrap/build-tools/cross-tools/build-tools-gawk/plan.sh, packages/bootstrap/build-tools/cross-tools/build-tools-ncurses/.hab-plan-config.toml, packages/bootstrap/build-tools/cross-tools/build-tools-ncurses/plan.sh, packages/bootstrap/build-tools/cross-tools/build-tools-tar/plan.sh, packages/bootstrap/stage1/ncurses/.hab-plan-config.toml, packages/bootstrap/stage1/ncurses/plan.sh, packages/development/libraries/ncurses/.hab-plan-config.toml, packages/development/libraries/ncurses/plan.sh, packages/tools/archivers/tar/plan.sh, packages/tools/misc/findutils/plan.sh, packages/tools/text/gawk/.hab-plan-config.toml, packages/tools/text/gawk/plan.sh
=> fixes for various license errors

packages/tools/networking/haproxy/.hab-plan-config.toml, packages/tools/networking/haproxy/config/haproxy.conf, packages/tools/networking/haproxy/default.toml, packages/tools/networking/haproxy/plan.sh
https://chefio.atlassian.net/browse/CHEF-11686
=> Adding haproxy with version 2.8.5 [CHEF-11686]

packages/tools/system/runit/plan.sh
https://chefio.atlassian.net/browse/CHEF-11793
=> Adding runit package with version 2.1.2 [CHEF-11793]

packages/tools/security/firejail/.hab-plan-config.toml, packages/tools/security/firejail/plan.sh
=> [firejail] added v0.9.72

packages/bootstrap/build-tools/cross-tools/build-tools-coreutils/.hab-plan-config.toml, packages/bootstrap/build-tools/cross-tools/build-tools-findutils/.hab-plan-config.toml, packages/bootstrap/build-tools/cross-tools/build-tools-gawk/.hab-plan-config.toml
adding missed rules for license issues
=> adding missed rules for license issues

packages/bootstrap/build-tools/cross-tools/build-tools-sed/.hab-plan-config.toml, packages/tools/text/gawk/.hab-plan-config.toml, packages/tools/text/sed/.hab-plan-config.toml
Adding back missing-license and license-not-found fixes
=> Adding rules for license fixes

packages/applications/editors/vim/.hab-plan-config.toml, packages/bootstrap/build-tools/cross-tools/build-tools-gzip/.hab-plan-config.toml, packages/bootstrap/build-tools/cross-tools/build-tools-tar/.hab-plan-config.toml, packages/development/libraries/readline/.hab-plan-config.toml, packages/tools/archivers/tar/.hab-plan-config.toml, packages/tools/compression/gzip/.hab-plan-config.toml, packages/tools/misc/findutils/.hab-plan-config.toml
Adding back rules for build errors.
=> Fixing some more license issues for packages

packages/bootstrap/stage0/go/.hab-plan-config.toml, packages/bootstrap/stage0/go/cacerts.patch, packages/bootstrap/stage0/go/plan.sh, packages/development/compilers/go/19/.hab-plan-config.toml, packages/development/compilers/go/19/cacerts.patch, packages/development/compilers/go/19/plan.sh, packages/development/compilers/go/21/.hab-plan-config.toml, packages/development/compilers/go/21/cacerts.patch, packages/development/compilers/go/21/plan.sh
https://chefio.atlassian.net/browse/CHEF-12004
=> Go with go-stage0, go19 and go21 packages added [CHEF-12004]

packages/applications/servers/dex/config/config.yml, packages/applications/servers/dex/default.toml, packages/applications/servers/dex/hooks/init, packages/applications/servers/dex/hooks/run, packages/applications/servers/dex/plan.sh
https://chefio.atlassian.net/browse/CHEF-12030
=> Adding package dex with version 2.38.0 [CHEF-12030]

packages/tools/security/certstrap/plan.sh
=> [certstrap] added v1.3.0

packages/bootstrap/build-tools/cross-tools/build-tools-glibc/CVE-2022-39046.patch, packages/bootstrap/build-tools/cross-tools/build-tools-glibc/CVE-2023-0687.patch, packages/bootstrap/build-tools/cross-tools/build-tools-glibc/CVE-2023-4911.patch, packages/bootstrap/build-tools/cross-tools/build-tools-glibc/CVE-2023-6246.patch, packages/bootstrap/build-tools/cross-tools/build-tools-glibc/plan.sh, packages/bootstrap/stage0/glibc/CVE-2022-39046.patch, packages/bootstrap/stage0/glibc/CVE-2023-0687.patch, packages/bootstrap/stage0/glibc/CVE-2023-4911.patch, packages/bootstrap/stage0/glibc/CVE-2023-6246.patch, packages/bootstrap/stage0/glibc/plan.sh, packages/development/libraries/glibc/CVE-2022-39046.patch, packages/development/libraries/glibc/CVE-2023-0687.patch, packages/development/libraries/glibc/CVE-2023-4911.patch, packages/development/libraries/glibc/CVE-2023-6246.patch, packages/development/libraries/glibc/plan.sh
applying CVE patches to glibc2.36
=> applying CVE patches to glibc2.36

packages/bootstrap/build-tools/cross-tools/build-tools-bash-static/.hab-plan-config.toml, packages/bootstrap/build-tools/cross-tools/build-tools-bash-static/plan.sh, packages/shells/bash/shared/.hab-plan-config.toml, packages/shells/bash/shared/plan.sh, packages/shells/bash/static/.hab-plan-config.toml, packages/shells/bash/static/plan.sh
=> Update bash to 5.2.21

packages/tools/networking/netcat-openbsd/plan.sh
=> update patches link

packages/development/libraries/local-lib/plan.sh, packages/development/tools/misc/cpanminus/plan.sh, packages/development/tools/misc/sqitch/.hab-plan-config.toml, packages/development/tools/misc/sqitch/plan.sh
=> [sqitch] added core/sqitch, core/cpanminus, core/local-lib

packages/bootstrap/build-tools/host-tools/native-busybox-static/.hab-plan-config.toml, packages/bootstrap/stage1/coreutils/.hab-plan-config.toml, packages/os-specific/linux/busybox/static/.hab-plan-config.toml, packages/tools/misc/coreutils/.hab-plan-config.toml
=> fix license errors

packages/bootstrap/build-tools/cross-tools/build-tools-glibc/plan.sh, packages/bootstrap/stage0/glibc/plan.sh, packages/development/libraries/glibc/plan.sh
=> fix glibc link issue

packages/applications/servers/nginx/plan.sh, packages/bootstrap/build-tools/cross-tools/build-tools-make/.hab-plan-config.toml, packages/bootstrap/build-tools/cross-tools/build-tools-make/plan.sh, packages/bootstrap/build-tools/cross-tools/build-tools-openssl/.hab-plan-config.toml, packages/bootstrap/build-tools/cross-tools/build-tools-openssl/plan.sh, packages/bootstrap/build-tools/target-tools/build-tools-python/.hab-plan-config.toml, packages/bootstrap/build-tools/target-tools/build-tools-python/plan.sh, packages/development/interpreters/erlang/plan.sh, packages/development/interpreters/ruby/3_3/plan.sh, packages/development/libraries/openssl/plan.sh, packages/development/tools/misc/patchelf/plan.sh
change versions for build-tools to match standard packages
=> add license files

packages/bootstrap/build-tools/cross-tools/build-tools-rust/.hab-plan-config.toml, packages/bootstrap/build-tools/cross-tools/build-tools-rust/plan.sh, packages/bootstrap/build-tools/cross-tools/build-tools-rust/rustc-wrapper.sh, packages/bootstrap/build-tools/cross-tools/build-tools-toml-cli/plan.sh, packages/bootstrap/build-tools/cross-tools/build-tools-zlib/.hab-plan-config.toml, packages/bootstrap/build-tools/cross-tools/build-tools-zlib/plan.sh, packages/bootstrap/build-tools/host-tools/native-rust/x86_64-linux/.hab-plan-config.toml, packages/bootstrap/build-tools/host-tools/native-rust/x86_64-linux/plan.sh, packages/tools/habitat/hab-launcher/plan.sh, packages/tools/habitat/hab-sup/plan.sh, packages/tools/habitat/hab/plan.sh
https://chefio.atlassian.net/browse/CHEF-12053
=> Bumping native-rust and rust packages to 1.75.0 [CHEF-12053]

packages/development/tools/misc/pester/plan.ps1
=> CHEF-13086 add pester 5.5.0

packages/data/cacerts/plan.ps1
=> CHEF-13102 add cacerts for win

packages/development/compilers/go/1_22/plan.ps1
CHEF-13134 add go1.22.4 for win
=> CHEF-13134 add go1.22.4 for win

packages/tools/misc/shellcheck/plan.ps1
https://chefio.atlassian.net/browse/CHEF-13201
=> Added shellcheck for Windows[CHEF-13201]

packages/development/haskell-modules/cabal-install/plan.ps1
https://chefio.atlassian.net/browse/CHEF-13200
=> Added cabal-install for Windows[CHEF-13200]

packages/tools/package-management/yarn/plan.ps1
https://chefio.atlassian.net/browse/CHEF-13137
=> Added yarn package for Windows[CHEF-13137]

packages/applications/virtualization/docker-credential-helper/plan.ps1
https://chefio.atlassian.net/browse/CHEF-13130
=> Added docker-credential-helper for Windows[CHEF-13130]

packages/development/tools/continuous-integration/buildkite-cli/plan.ps1
https://chefio.atlassian.net/browse/CHEF-13132
=> Added buildkite-cli for Windows[CHEF-13132]

packages/applications/servers/nginx/plan.ps1
CHEF-13103 add nginx 1.26.0 for win
=> CHEF-13103 add nginx 1.26.0 for win

packages/shells/powershell/plan.ps1
=> CHEF-13087 add powershell for win 7.5.0

packages/development/compilers/corretto/11/plan.ps1
CHEF-13129 add corretto11 11.0.23.9.1 for win
=> CHEF-13129 add corretto11 11.0.23.9.1 for win

packages/development/tools/build-managers/maven/plan.ps1
CHEF-13133 add maven3.9.7 for win
=> CHEF-13133 add maven3.9.7 for win

packages/development/libraries/libsodium/plan.ps1
CHEF-13136 add libsodium1.0.20 for win
=> CHEF-13136 add libsodium1.0.20 for win

packages/applications/version-management/git/plan.ps1
https://chefio.atlassian.net/browse/CHEF-13090
=> Adding git for Windows[CHEF-13090]

packages/development/compilers/nasm/plan.ps1
https://chefio.atlassian.net/browse/CHEF-13107
=> Adding nasm for Windows[CHEF-13107]

packages/tools/text/jq/static/plan.ps1
https://chefio.atlassian.net/browse/CHEF-13108
=> jq-static added for Windows[CHEF-13108]

packages/development/tools/build-managers/cmake/plan.ps1
https://chefio.atlassian.net/browse/CHEF-13114
=> Added cmake for Winodws[CHEF-13114]

packages/applications/virtualization/docker/plan.ps1
https://chefio.atlassian.net/browse/CHEF-13127
=> Added docker for Windows[CHEF-13127]

packages/development/tools/misc/aws-cli/plan.ps1
=> [aws-cli] added v1.32.113

packages/development/compilers/ghc/plan.ps1
=> [ghc] added v9.10.1

packages/development/interpreters/node/plan.ps1
=> [node] added v20.13.1

packages/development/interpreters/python/plan.ps1
=> [python] added v3.12.0

packages/development/tools/nuget/plan.ps1
=> [nuget] added v6.10.0

packages/development/tools/misc/wix/plan.ps1
=> [wix] added v5.0.0

packages/development/tools/misc/lessmsi/plan.ps1
=> [lessmsi] add v2.0.1

packages/tools/misc/sccache/hooks/run, packages/tools/misc/sccache/plan.sh
https://chefio.atlassian.net/browse/CHEF-13293
=> Added sccache with version 0.8.1[CHEF-13293]

packages/development/libraries/libarchive/plan.sh
https://chefio.atlassian.net/browse/CHEF-13295
=> libarchive bumped from 3.6.2 to 3.7.4[CHEF-13295]

packages/development/libraries/protobuf-rust/plan.sh
https://chefio.atlassian.net/browse/CHEF-13294
=> protobuf-rust package with version 1.7.5 added[CHEF-13294]

packages/development/compilers/go/1_22/plan.ps1
change go1_22 package name for windows
=> change go1_22 package name for windows

packages/applications/servers/dns/bind/.hab-plan-config.toml, packages/applications/servers/dns/bind/plan.sh
https://chefio.atlassian.net/browse/CHEF-13683
=> bind package added [CHEF-13683]

packages/development/libraries/boost/.hab-plan-config.toml, packages/development/libraries/boost/plan.sh
https://chefio.atlassian.net/browse/CHEF-13686
=> boost package added for linux [CHEF-13686]

packages/development/libraries/bdwgc/.hab-plan-config.toml, packages/development/libraries/bdwgc/plan.sh
https://chefio.atlassian.net/browse/CHEF-13700
=> bdwgc package added for linux [CHEF-13700]

packages/development/tools/build-managers/ninja/.hab-plan-config.toml, packages/development/tools/build-managers/ninja/plan.sh
https://chefio.atlassian.net/browse/CHEF-13747
=> ninja bumped from 1.11.1 to 1.12.1 [CHEF-13747]

packages/os-specific/linux/numactl/.hab-plan-config.toml, packages/os-specific/linux/numactl/plan.sh
https://chefio.atlassian.net/browse/CHEF-13749
=> numactl added for linux[CHEF-13749]

packages/development/libraries/alsa-lib/.hab-plan-config.toml, packages/development/libraries/alsa-lib/plan.sh
https://chefio.atlassian.net/browse/CHEF-13578
=> alsa-lib package added for linux[CHEF-13578]

packages/development/interpreters/node/plan.sh
=> arm changes for node

packages/bootstrap/build-tools/host-tools/native-rust/aarch64-linux/.hab-plan-config.toml, packages/bootstrap/build-tools/host-tools/native-rust/aarch64-linux/plan.sh
=> update rust for arm

packages/bootstrap/stage1/maven/.hab-plan-config.toml, packages/bootstrap/stage1/maven/plan.sh, packages/development/tools/build-managers/maven/.hab-plan-config.toml, packages/development/tools/build-managers/maven/plan.sh
https://chefio.atlassian.net/browse/CHEF-13581
=> maven package added for linux[CHEF-13581]

packages/tools/misc/lttng-ust/.hab-plan-config.toml, packages/tools/misc/lttng-ust/plan.sh
https://chefio.atlassian.net/browse/CHEF-13755
=> lttng-ust package added for linux [CHEF-13755]

packages/development/libraries/lcms2/.hab-plan-config.toml, packages/development/libraries/lcms2/plan.sh
https://chefio.atlassian.net/browse/CHEF-13751
=> lcms2 package addded for linux[CHEF-13751]

packages/development/libraries/nspr/.hab-plan-config.toml, packages/development/libraries/nspr/plan.sh
https://chefio.atlassian.net/browse/CHEF-13748
=> nspr package added for linux [CHEF-13748]

packages/development/tools/misc/avisynthplus/plan.sh
https://chefio.atlassian.net/browse/CHEF-13837
=> avisynthplus package added for linux [CHEF-13837]

packages/development/libraries/nettle/.hab-plan-config.toml, packages/development/libraries/nettle/plan.sh
https://chefio.atlassian.net/browse/CHEF-13745
=> nettle packade added for linux [CHEF-13745]

packages/development/libraries/libatomic_ops/.hab-plan-config.toml, packages/development/libraries/libatomic_ops/plan.sh
https://chefio.atlassian.net/browse/CHEF-13699
=> libatomic_ops package added for linux [CHEF-13699]

packages/tools/system/sudo/.hab-plan-config.toml, packages/tools/system/sudo/plan.sh
=> [sudo] added v1.9.15p5

packages/userspace-rcu/.hab-plan-config.toml, packages/userspace-rcu/plan.sh
=> [userspace-rcu] added v0.14.0

packages/tools/misc/check/.hab-plan-config.toml, packages/tools/misc/check/plan.sh
https://chefio.atlassian.net/browse/CHEF-13852
=> check package added for linux[CHEF-13852]

packages/development/libraries/apr/.hab-plan-config.toml, packages/development/libraries/apr/plan.sh
https://chefio.atlassian.net/browse/CHEF-13833
=> apr package added for linux[CHEF-13833]

packages/development/libraries/freetype/.hab-plan-config.toml, packages/development/libraries/freetype/plan.sh
https://chefio.atlassian.net/browse/CHEF-13579
=> freetype package added for linux[CHEF-13579]

packages/development/libraries/apr-util/.hab-plan-config.toml, packages/development/libraries/apr-util/plan.sh
https://chefio.atlassian.net/browse/CHEF-13834
=> apr-util package added for linux[CHEF-13834]

packages/development/libraries/libice/.hab-plan-config.toml, packages/development/libraries/libice/plan.sh
https://chefio.atlassian.net/browse/CHEF-13869
=> libice package added for linux [CHEF-13869]

packages/tools/misc/elfutils/.hab-plan-config.toml, packages/tools/misc/elfutils/plan.sh
https://chefio.atlassian.net/browse/CHEF-13867
=> elfutils package added for linux [CHEF-13867]

packages/os-specific/linux/iptables/.hab-plan-config.toml, packages/os-specific/linux/iptables/plan.sh
https://chefio.atlassian.net/browse/CHEF-13845
=> iptables package added for linux[CHEF-13845]

packages/os-specific/linux/net-tools/.hab-plan-config.toml
=> build changes for net-tools

packages/development/libraries/libpciaccess/.hab-plan-config.toml, packages/development/libraries/libpciaccess/plan.sh
https://chefio.atlassian.net/browse/CHEF-13874
=> libpciaccess package added for linux[CHEF-13874]

packages/development/libraries/libgcrypt/.hab-plan-config.toml, packages/development/libraries/libgcrypt/plan.sh
https://chefio.atlassian.net/browse/CHEF-13872
=> libgcrypt package added to linux[CHEF-13872]

packages/development/interpreters/lua/.hab-plan-config.toml, packages/development/interpreters/lua/plan.sh
https://chefio.atlassian.net/browse/CHEF-13887
=> lua package added for linux [CHEF-13887]

packages/development/libraries/libpcap/.hab-plan-config.toml, packages/development/libraries/libpcap/plan.sh
https://chefio.atlassian.net/browse/CHEF-13871
=> libpcap package added for linux[CHEF-13871]

packages/tools/networking/netcat/plan.sh
https://chefio.atlassian.net/browse/CHEF-13916
=> netcat package added for linux [CHEF-13916]

packages/development/libraries/libsm/.hab-plan-config.toml, packages/development/libraries/libsm/plan.sh
https://chefio.atlassian.net/browse/CHEF-13885
=> libsm package added for linux[CHEF-13885]

packages/development/libraries/libtasn1/.hab-plan-config.toml, packages/development/libraries/libtasn1/plan.sh
https://chefio.atlassian.net/browse/CHEF-13886
=> libtasn1 package added for linux[CHEF-13886]

packages/os-specific/linux/busybox/shared/.hab-plan-config.toml, packages/os-specific/linux/busybox/shared/plan.sh
https://chefio.atlassian.net/browse/CHEF-13920
=> busybox package added for linux[CHEF-13920]

packages/development/libraries/npth/.hab-plan-config.toml, packages/development/libraries/npth/plan.sh
https://chefio.atlassian.net/browse/CHEF-13982
=> npath package added for gnupg[CHEF-13982]

packages/development/libraries/popt/.hab-plan-config.toml, packages/development/libraries/popt/plan.sh
https://chefio.atlassian.net/browse/CHEF-13924
=> popt package added for linux[CHEF-13924]

packages/development/libraries/openssl/plan.sh
=> arm changes for openssl to resolve wget error

packages/tools/misc/lsof/.hab-plan-config.toml, packages/tools/misc/lsof/plan.sh
https://chefio.atlassian.net/browse/CHEF-13962
=> lsof package added for linux[CHEF-13962]

packages/applications/misc/gnupg/.hab-plan-config.toml, packages/applications/misc/gnupg/plan.sh
https://chefio.atlassian.net/browse/CHEF-13977
=> gnupg package added for linux[CHEF-13977]

packages/tools/habitat/hab-launcher/.hab-plan-config.toml
build changes for hab launcher
=> build changes for hab launcher

packages/development/libraries/krb5/.hab-plan-config.toml, packages/development/libraries/krb5/plan.sh
https://chefio.atlassian.net/browse/CHEF-14050
=> krb5 package added for linux[CHEF-14050]

packages/development/tools/build-managers/scons/plan.sh
=> [scons] added v4.6.0

packages/tools/package-management/yarn/plan.sh
=> [yarn] added v1.22.22

packages/development/libraries/openjpeg/.hab-plan-config.toml, packages/development/libraries/openjpeg/plan.sh
=> [openjpeg] add v2.5.2

packages/shells/powershell/plan.sh
=> [powershell] added v7.4.3

packages/development/compilers/go/1_22/plan.sh
=> [go] upgrade to v1.22.5

packages/development/interpreters/ruby/3_3/.hab-plan-config.toml
=> changes for ruby for arm

packages/os-specific/linux/libaio/.hab-plan-config.toml, packages/os-specific/linux/libaio/plan.sh
https://chefio.atlassian.net/browse/CHEF-14051
=> libaio package added for linux[CHEF-14051]

packages/os-specific/linux/libnl/.hab-plan-config.toml, packages/os-specific/linux/libnl/plan.sh
https://chefio.atlassian.net/browse/CHEF-14196
=> libnl package added for linux[CHEF-14196]

packages/tools/misc/autogen/.hab-plan-config.toml, packages/tools/misc/autogen/plan.sh
https://chefio.atlassian.net/browse/CHEF-14148
=> autogen package added for linux[CHEF-14148]

packages/development/interpreters/guile/.hab-plan-config.toml, packages/development/interpreters/guile/plan.sh
https://chefio.atlassian.net/browse/CHEF-14133
=> guile package added for linux[CHEF-14133]

packages/development/libraries/musl/.hab-plan-config.toml, packages/development/libraries/musl/plan.sh
https://chefio.atlassian.net/browse/CHEF-14250
=> musl package added for linux[CHEF-14250]

packages/os-specific/linux/kernel-headers/musl/.hab-plan-config.toml, packages/os-specific/linux/kernel-headers/musl/plan.sh
https://chefio.atlassian.net/browse/CHEF-14188
=> linux-headers-musl added for linux[CHEF-14188]

packages/development/tools/documentation/doxygen/.hab-plan-config.toml, packages/development/tools/documentation/doxygen/plan.sh
https://chefio.atlassian.net/browse/CHEF-14181
=> doxygen package added for linux[CHEF-14181]

packages/shells/powershell/.hab-plan-config.toml, packages/tools/networking/netcat/.hab-plan-config.toml
Configure missing check rules for powershell and netcat packages.
=> config missing rules

packages/tools/networking/openssh/.hab-plan-config.toml, packages/tools/networking/openssh/plan.sh
https://chefio.atlassian.net/browse/CHEF-14316
=> openssh bumped from 9.7 to 9.8[CHEF-14316]

packages/tools/package-management/dpkg/.hab-plan-config.toml, packages/tools/package-management/dpkg/plan.sh
https://chefio.atlassian.net/browse/CHEF-14342
=> dpkg package added for linux[CHEF-14342]

packages/development/libraries/protobuf-rust/plan.sh
build changes for protobuf-rust
=> build changes for protobuf-rust

packages/tools/networking/openssh/.hab-plan-config.toml, packages/tools/networking/openssh/plan.sh
=> upgrade openssh to 9.8p1

packages/tools/archivers/7zip/.hab-plan-config.toml, packages/tools/archivers/7zip/plan.sh
https://chefio.atlassian.net/browse/CHEF-14382
=> 7zip package added for linux[CHEF-14382]

packages/development/compilers/rust/glibc/plan.sh
This adds the musl target to the linux rust package which we had in core-plans and is required for building the hab cli and exporters.
=> add musl target to rust package

packages/applications/databases/minio/.hab-plan-config.toml, packages/applications/databases/minio/plan.sh
pkg_source value updated correctly to  linux-amd64
=> pkg_source value changed from linux-arm64 to linux-amd64

packages/development/libraries/fontconfig/.hab-plan-config.toml, packages/development/libraries/fontconfig/plan.sh
=> [fontconfig] added v2.15.0

packages/tools/networking/wget/static/plan.sh
=> [wget-static] added v1.24.5

packages/development/tools/misc/concourse/plan.ps1
=> [concourse] added v7.11.2

packages/development/libraries/musl/.hab-plan-config.toml, packages/development/libraries/musl/plan.sh
=> add musl for arm

packages/development/interpreters/node/.hab-plan-config.toml, packages/development/interpreters/node/plan.sh
=> bump node to 18.20.4 for arm

packages/bootstrap/build-tools/cross-tools/build-tools-rust/aarch64-linux/.hab-plan-config.toml, packages/bootstrap/build-tools/cross-tools/build-tools-rust/aarch64-linux/plan.sh, packages/bootstrap/build-tools/host-tools/native-rust/aarch64-linux/.hab-plan-config.toml, packages/bootstrap/build-tools/host-tools/native-rust/aarch64-linux/plan.sh
bump native and buildtools rust to 1.79.0
=> bump native and buildtools rust to 1.79.0

packages/tools/security/certstrap/plan.sh
=> arm changes for certstrap

packages/development/compilers/rust/glibc/plan.ps1
https://chefio.atlassian.net/browse/CHEF-13274
=> rust package added for Windows[CHEF-13274]

packages/development/libraries/openssl/plan.ps1
https://chefio.atlassian.net/browse/CHEF-14785
=> openssl package added for Windows[CHEF-14785]

packages/tools/compression/bzip2/plan.ps1
https://chefio.atlassian.net/browse/CHEF-14784
=> bzip2 package added for Windows[CHEF-14784]

packages/tools/admin/visual-cpp-redist-2022/plan.ps1
https://chefio.atlassian.net/browse/CHEF-14783
=> Adding visual-cpp-redist-2022 package for Windows[CHEF-14783]

packages/development/libraries/zlib/glibc/plan.ps1
https://chefio.atlassian.net/browse/CHEF-14752
=> zlib package added for Windows[CHEF-14752]

packages/os-specific/windows/sdk/11/README.md, packages/os-specific/windows/sdk/11/plan.ps1
https://chefio.atlassian.net/browse/CHEF-14751
=> windows-11-sdk package added for Windows[CHEF-14571]

packages/development/libraries/zeromq/plan.ps1
[CHEF-14771](https://chefio.atlassian.net/browse/CHEF-14771)
[CHEF-14771]: https://chefio.atlassian.net/browse/CHEF-14771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> zeromq package added for Windows[CHEF-14771]

packages/development/libraries/libarchive/plan.ps1
https://chefio.atlassian.net/browse/CHEF-14796
=> libarchive package added for Windows[CHEF-14796]

packages/tools/admin/visual-build-tools-2022/plan.ps1
https://chefio.atlassian.net/browse/CHEF-14628
=> visual build tools 2022 package added for Windows[CHEF-14628]

packages/tools/text/raml2html/plan.ps1, packages/tools/text/raml2html/raml2html.bat
https://chefio.atlassian.net/browse/CHEF-13100
=> Added raml2html package for Windows[CHEF-13100]

packages/tools/misc/asciinema/plan.ps1
https://chefio.atlassian.net/browse/CHEF-13099
=> Adding asciinema for Windows[chef-13099]

packages/development/tools/packer/plan.ps1
https://chefio.atlassian.net/browse/CHEF-13110
=> Added packer for Windows[CHEF-13110]

packages/misc/psscriptanalyzer/plan.ps1
https://chefio.atlassian.net/browse/CHEF-13112
=> Added psscriptanayzer for Windows[CHEF-13112]

packages/development/tools/continuous-integration/buildkite-agent/plan.ps1
https://chefio.atlassian.net/browse/CHEF-13126
=> Added buildkite-agent for Windows[CHEF-13126]

packages/tools/admin/innounp/plan.ps1
https://chefio.atlassian.net/browse/CHEF-13197
=> Added innounp package for Windows[CHEF-13197]

packages/development/tools/build-managers/meson/plan.sh
=> [meson] added v1.5.0

packages/development/libraries/pixman/.hab-plan-config.toml, packages/development/libraries/pixman/plan.sh
=> [pixman] added v0.43.4

packages/development/libraries/libdrm/.hab-plan-config.toml, packages/development/libraries/libdrm/plan.sh
=> [libdrm] added v2.4.122

packages/applications/servers/dbus/.hab-plan-config.toml, packages/applications/servers/dbus/plan.sh
=> [dbus] added v1.14.10

packages/development/libraries/gnutls/.hab-plan-config.toml, packages/development/libraries/gnutls/plan.sh
=> [gnutls] added v3.7.11

packages/development/libraries/p11-kit/.hab-plan-config.toml, packages/development/libraries/p11-kit/plan.sh
=> [p11-kit] added v0.25.5

packages/development/compilers/dotnet/sdk/plan.ps1
https://chefio.atlassian.net/browse/CHEF-14822
=> dotnet-core-sdk package added for Windows[CHEF-14822]

packages/development/libraries/protobuf/plan.ps1
https://chefio.atlassian.net/browse/CHEF-14797
=> Added protobuf package for Windows[CHEF-14797]

packages/misc/ps-lock/PSLock.psd1, packages/misc/ps-lock/PSLock.psm1, packages/misc/ps-lock/README.md, packages/misc/ps-lock/plan.ps1
https://chefio.atlassian.net/browse/CHEF-14812
=> ps-lock package added for Windows[CHEF-14812]

packages/bootstrap/build-tools/cross-tools/build-tools-rust/.hab-plan-config.toml, packages/bootstrap/build-tools/cross-tools/build-tools-rust/plan.sh, packages/bootstrap/build-tools/host-tools/native-rust/x86_64-linux/.hab-plan-config.toml, packages/bootstrap/build-tools/host-tools/native-rust/x86_64-linux/plan.sh
https://chefio.atlassian.net/browse/CHEF-14434
=> native-rust and build-tool-rust bumped to 1.79.0[CHEF-14434]

packages/applications/databases/postgresql/15/client/plan.ps1
https://chefio.atlassian.net/browse/CHEF-14850
=> postgresql-client package added for Windows[CHEF-14850]

packages/data/cacerts/plan.ps1
=> parse error fix of pem file

packages/development/compilers/nasm/plan.sh
=> [nasm] added v2.16.03

packages/development/tools/misc/avisynthplus/plan.sh
=> [avisynthplus] fix for missing version.h

packages/tools/text/harfbuzz/.hab-plan-config.toml, packages/tools/text/harfbuzz/plan.sh
=> [harfbuzz] added v9.0.0

packages/development/libraries/glib/.hab-plan-config.toml, packages/development/libraries/glib/plan.sh
=> [glib] added v2.81.0

packages/development/libraries/glib/.hab-plan-config.toml, packages/development/libraries/glib/plan.sh
=> [glib] fix for license errors

packages/os-specific/linux/iproute2/.hab-plan-config.toml, packages/os-specific/linux/iproute2/plan.sh
https://chefio.atlassian.net/browse/CHEF-13846
=> iproute2 package added for linux[CHEF-13846]

packages/development/libraries/nss/.hab-plan-config.toml, packages/development/libraries/nss/plan.sh
=> [nss] upgraded to v3.102

packages/applications/databases/postgresql/15/extensions/postgis/.hab-plan-config.toml, packages/development/libraries/ffmpeg/.hab-plan-config.toml, packages/development/libraries/gnutls/.hab-plan-config.toml, packages/os-specific/linux/libnl/.hab-plan-config.toml
Fixed the missing-license and license-not-found issues for some packages.
=> Fixing the missing-license and license-not-found for some packages

packages/tools/security/vault/.hab-plan-config.toml, packages/tools/security/vault/config/settings.hcl, packages/tools/security/vault/default.toml, packages/tools/security/vault/hooks/init, packages/tools/security/vault/hooks/run, packages/tools/security/vault/plan.sh
=> [vault] added v1.17.3

packages/development/compilers/dotnet/framework-4.8.1/plan.ps1
Adding a package for .net framework 4.8.1.
=> Adding dotnet framework 4.8.1 support

packages/development/interpreters/ruby/3_4/.hab-plan-config.toml, packages/development/interpreters/ruby/3_4/plan.sh
CHEF-11646-add-ruby3.4-preview
=> CHEF-11646-add-ruby3.4-preview

packages/development/interpreters/ruby/3_1/.hab-plan-config.toml, packages/development/interpreters/ruby/3_1/plan.sh
https://chefio.atlassian.net/browse/CHEF-15295
Bumping from 3.1.3 to 3.1.6 for LTS-2024 channel.
=> ruby3_1 bumped from 3.1.3 to 3.1.6 for LTS-2024 channel [CHEF-15295]

packages/development/compilers/dotnet/core/.hab-plan-config.toml, packages/development/compilers/dotnet/core/plan.sh
CHEF-15494 add dotnet-core(runtime) 8.0.8
=> CHEF-15494 add dotnet-core 8.0.8

packages/tools/misc/scaffolding-base/lib/scaffolding.sh, packages/tools/misc/scaffolding-base/plan.sh
=> [scaffolding-base] added v0.1.0

packages/applications/databases/mongodb/.hab-plan-config.toml, packages/applications/databases/mongodb/config/mongod.conf, packages/applications/databases/mongodb/default.toml, packages/applications/databases/mongodb/hooks/init, packages/applications/databases/mongodb/plan.sh
=> [mongodb] added v18.1.8

packages/applications/databases/mysql/client/.hab-plan-config.toml, packages/applications/databases/mysql/client/plan.sh
=> [mysql-client] added v8.4.0

packages/development/interpreters/ruby/3_1/.hab-plan-config.toml, packages/development/interpreters/ruby/3_1/plan.sh
https://progresssoftware.atlassian.net/browse/CHEF-16025
Adding ffi and ffi-libarchive gems to fix runtime errors for chef19
=> ffi and ffi-libarchive gems added for fixing runtime errors for chef19[CHEF-16025]

packages/applications/virtualization/runc/plan.sh
https://progresssoftware.atlassian.net/browse/CHEF-16033
runc package is required for builldah package.
=> runc package required for building buildah package[CHEF-16033]

packages/tools/misc/scaffolding-go/.hab-plan-config.toml, packages/tools/misc/scaffolding-go/lib/go_module.sh, packages/tools/misc/scaffolding-go/lib/gopath_mode.sh, packages/tools/misc/scaffolding-go/lib/scaffolding.sh, packages/tools/misc/scaffolding-go/plan.sh
https://progresssoftware.atlassian.net/browse/CHEF-16034
Required for building buildah package.
=> scaffolding-go required for buildah package[CHEF-16034]

packages/development/interpreters/ruby/3_3/plan.sh, packages/development/tools/misc/bundler/.hab-plan-config.toml, packages/development/tools/misc/bundler/plan.sh
=> [bundler] added v2.5.19

packages/os-specific/linux/devicemapper/.hab-plan-config.toml, packages/os-specific/linux/devicemapper/plan.sh
=> add devicemapper

packages/development/tools/buildah/.hab-plan-config.toml, packages/development/tools/buildah/plan.sh
https://progresssoftware.atlassian.net/browse/CHEF-16074
https://progresssoftware.atlassian.net/browse/CHEF-16008
=> buildah package added builder[CHEF-16074]

packages/applications/misc/gnupg/.hab-plan-config.toml, packages/applications/misc/gnupg/plan.sh, packages/development/libraries/gpgme/.hab-plan-config.toml, packages/development/libraries/gpgme/plan.sh, packages/development/libraries/libgcrypt/.hab-plan-config.toml, packages/development/libraries/libgcrypt/plan.sh, packages/development/libraries/libksba/.hab-plan-config.toml, packages/development/libraries/libksba/plan.sh, packages/development/libraries/npth/.hab-plan-config.toml, packages/development/libraries/npth/plan.sh, packages/development/tools/buildah/.hab-plan-config.toml, packages/development/tools/buildah/plan.sh
https://progresssoftware.atlassian.net/browse/CHEF-16009
=> buildah and deps of buildah added for ARM [CHEF-16009]

packages/tools/networking/curl/plan.sh
https://progresssoftware.atlassian.net/browse/CHEF-16196
https://progresssoftware.atlassian.net/browse/CHEF-16075
=> curl bumped from 8.6.0 to 8.7.1 [CHEF-16196]

packages/tools/networking/curl/plan.sh
https://progresssoftware.atlassian.net/browse/CHEF-16197
https://progresssoftware.atlassian.net/browse/CHEF-16075
=> curl bumped from 8.6.0 to 8.7.1 [CHEF-16197]

packages/development/compilers/llvm/.hab-plan-config.toml, packages/development/compilers/llvm/plan.sh
https://progresssoftware.atlassian.net/browse/CHEF-16215
=> Adding llvm package with version 18.1.6 [CHEF-16215]

packages/development/libraries/openssl/plan.ps1
https://progresssoftware.atlassian.net/browse/CHEF-16026
=> Openssl downgraded to 3.0.9 from 3.3.1 for Windows[CHEF-16026

packages/tools/package-management/rpm/.hab-plan-config.toml, packages/tools/package-management/rpm/plan.sh
=> add rpm 4.18.2

packages/applications/servers/monitoring/prometheus/.hab-plan-config.toml, packages/applications/servers/monitoring/prometheus/TODO.txt, packages/applications/servers/monitoring/prometheus/config/prometheus.yml, packages/applications/servers/monitoring/prometheus/default.toml, packages/applications/servers/monitoring/prometheus/hooks/run, packages/applications/servers/monitoring/prometheus/plan.sh
https://progresssoftware.atlassian.net/browse/CHEF-16321
=> prometheus package added [CHEF-16321]

packages/development/libraries/libxml2/.hab-plan-config.toml, packages/development/libraries/libxml2/plan.sh
https://progresssoftware.atlassian.net/browse/CHEF-16339
=> libxml2 bumped to 2.11.5 from 2.10.3 [CHEF-16339]

packages/development/haskell-modules/cabal-install/plan.sh, packages/development/haskell-modules/happy/plan.sh
=> added happy and cabal-install

packages/development/haskell-modules/alex/plan.sh
=> [alex] added v3.5.1.0

packages/development/haskell-modules/shellcheck/.hab-plan-config.toml, packages/development/haskell-modules/shellcheck/plan.sh
=> [shellcheck] added v0.10.0

packages/applications/servers/monitoring/prometheus/.hab-plan-config.toml, packages/applications/servers/monitoring/prometheus/hooks/run, packages/development/libraries/gpgme/.hab-plan-config.toml
=> Fixing hab-auto-build errors

packages/applications/servers/dbus/.hab-plan-config.toml, packages/tools/security/firejail/.hab-plan-config.toml
=> Adding some more fixes for hab-auto-build

packages/applications/databases/mongodb/.hab-plan-config.toml
Fixing the hab-auto-build tool error for mongodb
=> Fixing the hab-auto-build tool errors

packages/development/libraries/openssl/glibc/cacert-path.patch, packages/development/libraries/openssl/glibc/plan.sh
changes to fetch default certfile of openssl from cacerts package
=> changes to fetch default certfile of openssl from cacerts package

category.json
=> updated package category for linux, windows and aarch

category.json
add corretto to maintainance cycle
=> add corretto to maintainance cycle

packages/development/interpreters/elixir/.hab-plan-config.toml, packages/development/interpreters/elixir/plan.sh
add elixir 1.17.3 to LTS.CHEF-16748
=> add elixir 1.17.3

category.json
add elixir to maintainance cycle
change gecode maintainance cycle
=> add elixir,update gecode in maintainance cycle

packages/development/interpreters/ruby/3_1/.hab-plan-config.toml, packages/development/interpreters/ruby/3_1/plan.sh
https://progresssoftware.atlassian.net/browse/CHEF-18357
https://progresssoftware.atlassian.net/browse/CHEF-18595
=> Fixing the ruby-shadow gem install issue CHEF[18357]
